version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-cansan2024}
      DATA_DIR: /app/data
      MAINTENANCE_MODE: ${MAINTENANCE_MODE:-false}
      MAINTENANCE_PASSWORD: ${MAINTENANCE_PASSWORD:-cansan2024}
    restart: unless-stopped
